apiVersion: apps/v1
kind: Deployment
metadata:
  name: lark1n-app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: lark1n-app
  template:
    metadata:
      labels:
        app: lark1n-app
    spec:
      containers:
      - name: app-bug-free-spoon
        image: ghcr.io/lark1n/bug-free-spoon:869d306a87d3cfdae7f4b4b6190bfd39abde6f66
        ports:
        - containerPort: 8080