name: Check
on: push
jobs:
   build_app:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - uses: actions/setup-go@v5
           with:
            go-version: '1.14'
            check-latest: true
         - run: go run oleksii
