name: Build
on: push
jobs:
  build_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        #распаковка репозитория
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true
      - name: build app
        run: go build -o oleksii .
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: oleksii-artifact
          path: oleksii
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: 
      - build_app
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          #ссылка на нужный репозиторий
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: oleksii-artifact
          path: /oleksii
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{github.repository}}:${{github.sha}}
          #более оптимальная запись, registry.com/repo:tag
          #ghcr.io/lark1n/bug-free-spoon:tags
          #$ {{github.sha}} дает нам уникальный номер версии, операясь на коммиты
