name: Build
on: push
jobs:
   build_app:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
         - uses: actions/setup-go@v5
           with:
            go-version: '1.22'
            check-latest: true
         - name: build app
           run: go build -o oleksii .
           env:
            GOOS: linux
            GOARCH: amd64
         - name: Upload Artifact
           uses: actions/upload-artifact@v4
           with:
            name: oleksii-artifact
            path: oleksii